[project]
name = "bot"
version = "0.1.0"
description = "Monitors the plants"
readme = "README.md"
authors = [
    { name = "Wildbush", email = "75509166+Wildbush76@users.noreply.github.com" },
]
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=25.1.0",
    "bleak>=3.0.2",
    "discord>=2.3.2",
    "matplotlib>=3.11.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
bot = "bot:run_bot"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = ["ruff>=0.16.6"]
